## **DECISION TREE ALGORITHM**

In [1]:
#Import libraries
import numpy as np
import pandas as pd


# LOADING DATASET

In [2]:
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()


In [3]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [5]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [6]:
#Creating Dataframe
df=pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])


In [7]:
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [8]:
df.shape

(569, 31)

In [9]:
df.columns

MultiIndex([(            'mean radius',),
            (           'mean texture',),
            (         'mean perimeter',),
            (              'mean area',),
            (        'mean smoothness',),
            (       'mean compactness',),
            (         'mean concavity',),
            (    'mean concave points',),
            (          'mean symmetry',),
            ( 'mean fractal dimension',),
            (           'radius error',),
            (          'texture error',),
            (        'perimeter error',),
            (             'area error',),
            (       'smoothness error',),
            (      'compactness error',),
            (        'concavity error',),
            (   'concave points error',),
            (         'symmetry error',),
            ('fractal dimension error',),
            (           'worst radius',),
            (          'worst texture',),
            (        'worst perimeter',),
            (             'worst a

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   (mean radius,)              569 non-null    float64
 1   (mean texture,)             569 non-null    float64
 2   (mean perimeter,)           569 non-null    float64
 3   (mean area,)                569 non-null    float64
 4   (mean smoothness,)          569 non-null    float64
 5   (mean compactness,)         569 non-null    float64
 6   (mean concavity,)           569 non-null    float64
 7   (mean concave points,)      569 non-null    float64
 8   (mean symmetry,)            569 non-null    float64
 9   (mean fractal dimension,)   569 non-null    float64
 10  (radius error,)             569 non-null    float64
 11  (texture error,)            569 non-null    float64
 12  (perimeter error,)          569 non-null    float64
 13  (area error,)               569 non

In [11]:
df.describe()

mean radius mean texture mean perimeter    mean area mean smoothness  \
count  569.000000   569.000000     569.000000   569.000000      569.000000   
mean    14.127292    19.289649      91.969033   654.889104        0.096360   
std      3.524049     4.301036      24.298981   351.914129        0.014064   
min      6.981000     9.710000      43.790000   143.500000        0.052630   
25%     11.700000    16.170000      75.170000   420.300000        0.086370   
50%     13.370000    18.840000      86.240000   551.100000        0.095870   
75%     15.780000    21.800000     104.100000   782.700000        0.105300   
max     28.110000    39.280000     188.500000  2501.000000        0.163400   

      mean compactness mean concavity mean concave points mean symmetry  \
count       569.000000     569.000000          569.000000    569.000000   
mean          0.104341       0.088799            0.048919      0.181162   
std           0.052813       0.079720            0.038803      0.027414   
min           0.019380       0.000000            0.000000      0.106000   
25%           0.064920       0.029560            0.020310      0.161900   
50%           0.092630       0.061540            0.033500      0.179200   
75%           0.130400       0.130700            0.074000      0.195700   
max           0.345400       0.426800            0.201200      0.304000   

      mean fractal dimension  ... worst texture worst perimeter   worst area  \
count             569.000000  ...    569.000000      569.000000   569.000000   
mean                0.062798  ...     25.677223      107.261213   880.583128   
std                 0.007060  ...      6.146258       33.602542   569.356993   
min                 0.049960  ...     12.020000       50.410000   185.200000   
25%                 0.057700  ...     21.080000       84.110000   515.300000   
50%                 0.061540  ...     25.410000       97.660000   686.500000   
75%                 0.066120  ...     29.720000      125.400000  1084.000000   
max                 0.097440  ...     49.540000      251.200000  4254.000000   

      worst smoothness worst compactness worst concavity worst concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.132369          0.254265        0.272188             0.114606   
std           0.022832          0.157336        0.208624             0.065732   
min           0.071170          0.027290        0.000000             0.000000   
25%           0.116600          0.147200        0.114500             0.064930   
50%           0.131300          0.211900        0.226700             0.099930   
75%           0.146000          0.339100        0.382900             0.161400   
max           0.222600          1.058000        1.252000             0.291000   

      worst symmetry worst fractal dimension      target  
count     569.000000              569.000000  569.000000  
mean        0.290076                0.083946    0.627417  
std         0.061867                0.018061    0.483918  
min         0.156500                0.055040    0.000000  
25%         0.250400                0.071460    0.000000  
50%         0.282200                0.080040    1.000000  
75%         0.317900                0.092080    1.000000  
max         0.663800                0.207500    1.000000  

[8 rows x 31 columns]

### **SPLIT DATA **

In [12]:
data1=df.copy()
X=data1.drop(columns=['target'],axis=1)
y=data1['target']

<ipython-input-12-4e5dc2f5ecbb>:2: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  X=data1.drop(columns=['target'],axis=1)


In [13]:
X.shape

(569, 30)

In [14]:
y.shape

(569, 1)

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=2020)
print("Shape of X_train",X_train.shape)
print("Shape of X_test",X_test.shape)
print("Shape of y_train",y_train.shape)
print("Shape of y_test",y_test.shape)

Shape of X_train (455, 30)
Shape of X_test (114, 30)
Shape of y_train (455, 1)
Shape of y_test (114, 1)


# **TRAIN DECISION TREE CLASSIFICATION MODEL**

In [16]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion="gini")
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [17]:
from sklearn.metrics import accuracy_score
y_pred=classifier.predict(X_test)
score=accuracy_score(y_test,y_pred)
accuracy=score*100
print(accuracy)

95.6140350877193


In [18]:
# Entropy
classifier_en=DecisionTreeClassifier(criterion="entropy")
classifier.fit(X_train,y_train)



DecisionTreeClassifier()

In [19]:
from sklearn.metrics import accuracy_score
y_pred=classifier.predict(X_test)
score=accuracy_score(y_test,y_pred)
accuracy=score*100
print(accuracy)


93.85964912280701


## **FEATURE SCALING**

In [20]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()


In [21]:
sc.fit(X_train)

StandardScaler()

In [22]:
X_train_sc=sc.transform(X_train)
X_test_sc=sc.transform(X_test)


In [23]:
classifier_sc=DecisionTreeClassifier(criterion="gini")
classifier_sc.fit(X_train_sc,y_train)
classifier_sc.score(X_test_sc,y_test)


0.956140350877193

## **Predict Cancer**

In [24]:
patient1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]

In [25]:
patient1=np.array([patient1])


array([0.])

In [27]:
pred=classifier.predict(patient1)
if pred[0] == 0:
  print('Patient has Cancer (malignant tumor)')
else:
  print('Patient has no Cancer (malignant benign)')

Patient has Cancer (malignant tumor)
